name: flutter_plugin_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 1.0.9
homepage: https://github.com/CrossPT/flutter_plugin_pdf_viewer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.0
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  numberpicker: ^2.1.2
  flutter_advanced_networkimage_2: any

flutter:
  plugin:
    androidPackage: pt.tribeiro.flutter_plugin_pdf_viewer
    pluginClass: FlutterPluginPdfViewerPlugin
